### ISSUE TITLE
TsConfigPathsPlugin should be under resolve: plugins: instead of plugins:

### ISSUE THREAD

**Issue by Umuril** [easy-webpack/config-typescript#16]
TypeScript was breaking all my configuration file because i (kinda) copy-pasted this code. Adding this plugin inside the plugins array changed his type which was no more a Configuration type. So i did a bit of search to understand the problem.

From @types/webpack

```typescript

interface Configuration {
...
plugins?: Plugin[];
}

abstract class Plugin implements Tapable.Plugin {
       apply(compiler: Compiler): void;
}
```
instead the plugin implements (from awesome-typescript-loader)

```typescript
const TsConfigPathsPlugin: typeof PathPlugin;

export declare class PathPlugin implements ResolverPlugin{
...
apply(resolver: Resolver): void;
}

export interface ResolverPlugin {
    apply(resolver: Resolver): void;
}
```

This is the first bug i have ever found, so I hope i'm doing all right, otherwise let me know.

**Comment by Umuril** [comment]
Another thing,
```typescript
const { TsConfigPathsPlugin, CheckerPlugin } = require('awesome-typescript-loader') // does not complain about typings
```
now he complains

**Comment by niieani** [comment]
Thanks!

**Comment by niieani** [comment]
Thanks!
