### ISSUE TITLE
Babel dependency

### ISSUE THREAD

**Issue by ngocvantran** [easy-webpack/config-typescript#3]
I see that babel is listed as dependency of this package. However, I don't think using Typescript in webpack needs Babel. Did I understood it incorrectly? In case it's not really needed, I'd appreciate it if you can remove babel dependency.

**Comment by ngocvantran** [comment]
Sorry, my bad. I found that awesome typescript does have the option to use babel, so it make sense to depend on babel in this case.

**Comment by niieani** [comment]
This is currently necessary to support await-async scenarios in ES5 output. Once TypeScript 2.1 is release, it won't be necessary anymore.
